/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import helper.ConnectionHelper;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suisei
 */
public class editMenu extends javax.swing.JFrame {

    /**
     * Creates new form editMenu
     */
    public editMenu() {
        initComponents();
        this.setTitle("Edit Produk");
        model = new DefaultTableModel();
        TableProduct.setModel(model);
        model.addColumn("ID");
        model.addColumn("Nama Produk");
        model.addColumn("Jumlah Stok");
        model.addColumn("Stok tersedia");
        model.addColumn("Stok terjual");
        model.addColumn("Tanggal Kadaluarsa");
        this.setLocationRelativeTo(null);
        //tanggalNow();
        tampil();
    }

    Connection conn = ConnectionHelper.getConnection();
    private DefaultTableModel model;
    
    private void tanggalNow(){
        Calendar cal = Calendar.getInstance();
        Date date=cal.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        kadaluarsaBox.setDateFormatString("dd/MM/yyyy");
        kadaluarsaBox.setDate(date);
    }
    
    private void reset(){
        txt_nama.setText("");
        txt_totalStock.setText("");
        txt_stockSold.setText("");
        txt_stockAva.setText("");
        txt_dibeli.setText("");
    }
    
    private void tampil(){
            try{
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                String query = "SELECT * FROM product WHERE product.id_product";
                Statement statement = (Statement) conn.createStatement();
                ResultSet result = statement.executeQuery(query);
                if (!result.next()) {
                    JOptionPane.showMessageDialog(this,"Data Kosong!","Notification",JOptionPane.WARNING_MESSAGE);
                }else{
                    while(result.next()){
                        Object[] o = new Object[6];
                        o[0] = result.getString("id_product");
                        o[1] = result.getString("product_name");
                        o[2] = result.getInt("total_stock");
                        o[3] = result.getInt("stock");
                        o[4] = result.getInt("sold_stock");
                        o[5] = result.getString("expiry_date");
                        
                        model.addRow(o);
                    }
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, ex);
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kadaluarsaBox = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txt_dibeli = new javax.swing.JTextField();
        hitungBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_totalStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_stockSold = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_stockAva = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProduct = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Edit Produk");

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama Produk");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tanggal Kadaluarsa");

        kadaluarsaBox.setDateFormatString("dd MM yyyy");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Jumlah yang Dibeli Konsumen");

        hitungBtn.setBackground(new java.awt.Color(255, 255, 255));
        hitungBtn.setText("Hitung");
        hitungBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama)
                    .addComponent(jLabel3)
                    .addComponent(kadaluarsaBox, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_dibeli)
                        .addGap(18, 18, 18)
                        .addComponent(hitungBtn)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kadaluarsaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dibeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitungBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Jumlah Stok");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Stok yang Tersedia");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Stok yang Terjual");

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(txt_totalStock, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(txt_stockSold)
                            .addComponent(jLabel6)
                            .addComponent(txt_stockAva))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addGap(40, 40, 40)
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(deleteBtn)
                        .addGap(39, 39, 39))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_totalStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addComponent(txt_stockSold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_stockAva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addGap(27, 27, 27))
        );

        TableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(323, 323, 323))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (txt_nama.getText().equals("")||txt_totalStock.getText().equals("")||txt_stockAva.getText().equals("")||txt_stockSold.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Harap Isi Semua Data!","Notification",JOptionPane.WARNING_MESSAGE);    
        }else{
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            kadaluarsaBox.setDateFormatString("dd/MM/yyyy");
            String strdate = dateFormat.format(kadaluarsaBox.getDate());
            String nama = txt_nama.getText();
            String totstock = txt_totalStock.getText();
            int jumlahstock = Integer.parseInt(totstock);
            String sold = txt_stockSold.getText();
            int terjual = Integer.parseInt(sold);
            String avai = txt_stockAva.getText();
            int tersedia = Integer.parseInt(avai);
                try {
//                    String queryId = "SELECT id_product FROM product ORDER BY id_product DESC LIMIT 1";
//                    try {
//                        Statement statement = conn.createStatement();
//                        ResultSet resultId = statement.executeQuery(queryId);
//                        while (resultId.next()) {
//                            int newId = resultId.getInt("id_product");
//                            admin.fixId = newId + 1;
//                        }
//                    } catch (SQLException ex) {
//                        JOptionPane.showMessageDialog(this, "gagal getId", "Failed", JOptionPane.ERROR_MESSAGE);
//                    }
                    String query = "INSERT INTO product(product_name, total_stock, stock, sold_stock, expiry_date) VALUES(?,?,?,?,?)";
                    PreparedStatement statement = (PreparedStatement) conn.prepareStatement(query);
                    statement.setString(1, nama);
                    statement.setInt(2, jumlahstock);
                    statement.setInt(3, tersedia);
                    statement.setInt(4, terjual);
                    statement.setString(5, strdate);
                    statement.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Berhasil Menambahkan!", "Success", JOptionPane.PLAIN_MESSAGE);
                    tampil();
                    reset();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Gagal Menambahkan! " + ex, "Failed", JOptionPane.WARNING_MESSAGE);
                }
            }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        kadaluarsaBox.setDateFormatString("dd/MM/yyyy");
        
        if (TableProduct.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,"Tabel Kosong!","Notification",JOptionPane.WARNING_MESSAGE);
        }else if(TableProduct.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this,"Pilih Data yang Akan Diubah!","Notification",JOptionPane.WARNING_MESSAGE);
        } else{
            String id_produk = model.getValueAt(TableProduct.getSelectedRow(),0).toString();
            String nama = txt_nama.getText();
            String strdate = dateFormat.format(kadaluarsaBox.getDate());
            String totstock = txt_totalStock.getText();
            int jumlahstock = Integer.parseInt(totstock);
            String sold = txt_stockSold.getText();
            int terjual = Integer.parseInt(sold);
            String avai = txt_stockAva.getText();
            int tersedia = Integer.parseInt(avai);

            String sql = "UPDATE product SET product_name=?,total_stock=?,stock=?,sold_stock=?,expiry_date=? WHERE id_product =?";
            try{
                PreparedStatement statement = (PreparedStatement)conn.prepareStatement(sql);
                statement.setString(1, nama);
                statement.setInt(2, jumlahstock);
                statement.setInt(3, Integer.parseInt(txt_stockAva.getText()));
                statement.setInt(4, Integer.parseInt(txt_stockSold.getText()));
                statement.setString(5, strdate);
                statement.setString(6, id_produk);
                
                statement.executeUpdate();
                reset();
                tampil();
                JOptionPane.showMessageDialog(this,"Berhasil Update!","Success",JOptionPane.PLAIN_MESSAGE);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Gagal Update! "+e,"Failed",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (TableProduct.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this,"Tabel Kosong!","Notification",JOptionPane.WARNING_MESSAGE);
        }else if(TableProduct.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this,"Pilih Data yang Akan Dihapus!","Notification",JOptionPane.WARNING_MESSAGE);
        }else{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this,"Apakah Anda Yakin Ingin Menghapus Produk?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM product WHERE id_product=?";
                try{
                    String id_produk = model.getValueAt(TableProduct.getSelectedRow(),0).toString(); //check
                    PreparedStatement statement = conn.prepareStatement(sql);
                    statement.setString(1, id_produk); //check
                    statement.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Data Berhasil Dihapus!","Success",JOptionPane.PLAIN_MESSAGE);
                    tampil();
                    reset();
                    
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(this,"Gagal Menghapus Data! "+e,"Failed",JOptionPane.ERROR_MESSAGE);    
                } 
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void TableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProductMouseClicked
        txt_nama.setText(model.getValueAt(TableProduct.getSelectedRow(),1).toString());
        txt_totalStock.setText(model.getValueAt(TableProduct.getSelectedRow(),2).toString());
        txt_stockAva.setText(model.getValueAt(TableProduct.getSelectedRow(),3).toString());
        txt_stockSold.setText(model.getValueAt(TableProduct.getSelectedRow(),4).toString());
        
        try{
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            Date createDate = null;
            createDate = df.parse(model.getValueAt(TableProduct.getSelectedRow(),5).toString());
            kadaluarsaBox.setDate(createDate);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_TableProductMouseClicked

    private void hitungBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBtnActionPerformed
        try{
            String str = txt_dibeli.getText();
            if (str.length()==0) {
                JOptionPane.showMessageDialog(this,"Isi jumlah yang dibeli terlebih dahulu!","Notification",JOptionPane.WARNING_MESSAGE);
            }else{
                String sold = txt_stockSold.getText();
                int terjual = Integer.parseInt(sold);
                
                String avai = txt_stockAva.getText();
                int tersedia = Integer.parseInt(avai);
                
                String beli, bought, sisa;
                int buy, soldED, leftOver, tersisa;
                
                //stok terjual
                beli = txt_dibeli.getText();
                buy = Integer.parseInt(beli);
                soldED = terjual + buy;
                
                //stok tersisa
                beli = txt_dibeli.getText();
                leftOver = Integer.parseInt(beli);
                tersisa = tersedia - leftOver;

                bought = String.valueOf(soldED);
                txt_stockSold.setText(bought);
                sisa = String.valueOf(tersisa);
                txt_stockAva.setText(sisa);
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Inputan harus angka!","Notification",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_hitungBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableProduct;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton hitungBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser kadaluarsaBox;
    private javax.swing.JTextField txt_dibeli;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_stockAva;
    private javax.swing.JTextField txt_stockSold;
    private javax.swing.JTextField txt_totalStock;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
